import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, Bot, FolderKanban, ShieldCheck, Smartphone, Users } from "lucide-react";

const labels = { gemini: "Gemini IA", githubActions: "GitHub Actions", eas: "Expo / EAS", stripe: "Stripe", stripePackages: "Packs de crédits" } as const;

export default function AdminControlCenter() {
  const { user } = useAuth();
  const { data, isLoading, error } = trpc.admin.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  if (user?.role !== "admin") return <DashboardLayout><div className="mx-auto max-w-xl p-6 sm:p-10"><div className="rounded-2xl border border-amber-200/15 bg-amber-200/[0.06] p-6"><ShieldCheck className="size-6 text-amber-200" /><h1 className="mt-4 text-xl font-semibold">Accès administrateur requis</h1><p className="mt-2 text-sm leading-6 text-zinc-400">Cette zone est réservée aux opérations Lakay et n’est pas visible par les utilisateurs normaux.</p></div></div></DashboardLayout>;
  const cards = data ? [{ label: "Utilisateurs", value: data.totals.users, icon: Users }, { label: "Projets", value: data.totals.projects, icon: FolderKanban }, { label: "Générations", value: data.totals.generations, icon: Bot }, { label: "Publications", value: data.totals.mobileJobs, icon: Smartphone }] : [];
  return <DashboardLayout><div className="mx-auto max-w-6xl p-4 sm:p-8"><div className="mb-7"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-emerald-300">Administration Lakay</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Pilotage de la plateforme</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Suivez les opérations, les intégrations et les signaux utiles sans exposer de secrets ni de données de projet.</p></div>{isLoading ? <div className="rounded-2xl border border-white/[0.08] p-8 text-sm text-zinc-500">Chargement des opérations…</div> : error ? <div className="rounded-2xl border border-rose-300/15 bg-rose-300/[0.06] p-5 text-sm text-rose-100">Les données d’administration ne sont pas disponibles pour le moment.</div> : <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(card => <div key={card.label} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4"><card.icon className="size-4 text-emerald-300" /><p className="mt-5 text-2xl font-semibold">{card.value}</p><p className="mt-1 text-xs text-zinc-500">{card.label}</p></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><div className="flex items-center gap-2"><Activity className="size-4 text-violet-300" /><h2 className="text-sm font-semibold">Connexions</h2></div><div className="mt-4 space-y-2">{Object.entries(data?.integrations || {}).map(([key, ready]) => <div key={key} className="flex items-center justify-between rounded-xl bg-black/15 px-3 py-2.5 text-sm"><span>{labels[key as keyof typeof labels]}</span><span className={ready ? "text-emerald-300" : "text-zinc-500"}>{ready ? "Connecté" : "À configurer"}</span></div>)}</div><p className="mt-4 text-xs leading-5 text-zinc-500">Les clés, jetons et secrets restent invisibles dans cette interface.</p></section><section className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5"><div className="flex items-center gap-2"><Users className="size-4 text-violet-300" /><h2 className="text-sm font-semibold">Dernières connexions</h2></div><div className="mt-4 space-y-2">{data?.recentUsers.map(member => <div key={member.id} className="flex items-center justify-between gap-3 rounded-xl bg-black/15 px-3 py-2.5"><div className="min-w-0"><p className="truncate text-sm">{member.name || member.email || "Membre Lakay"}</p><p className="truncate text-[11px] text-zinc-500">{member.role === "admin" ? "Administrateur" : "Membre"}</p></div><time className="shrink-0 text-[10px] text-zinc-600">{new Date(member.lastSignedIn).toLocaleDateString()}</time></div>)}</div></section></div></>}</div></DashboardLayout>;
}
