import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Globe2, Link2, Loader2, Monitor, ShieldCheck } from "lucide-react";
import { useLocation, useRoute } from "wouter";

export default function WebPublishPage() {
  const [, params] = useRoute("/projects/:projectId/publish/web");
  const projectId = params?.projectId ?? "";
  const [, navigate] = useLocation();
  const { data: project, isLoading: projectLoading } = trpc.projects.get.useQuery({ projectId }, { enabled: Boolean(projectId) });
  const { data: builder, isLoading: builderLoading } = trpc.builder.get.useQuery({ projectId }, { enabled: Boolean(projectId) });
  const hasBuild = Boolean(builder?.files.length);

  if (projectLoading || builderLoading) return <DashboardLayout><div className="grid min-h-[70vh] place-items-center"><Loader2 className="size-6 animate-spin text-emerald-300" /></div></DashboardLayout>;
  if (!project) return <DashboardLayout><div className="mx-auto max-w-md py-28 text-center"><h1 className="text-xl font-semibold text-white">Ce projet n’est pas disponible.</h1></div></DashboardLayout>;

  return <DashboardLayout><main className="min-h-screen bg-[#0b0d10] px-4 py-6 text-zinc-100 sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl"><button onClick={() => navigate(`/projects/${projectId}/publish`)} className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"><ArrowLeft className="size-4" />Centre de publication</button><header className="mt-7 rounded-[28px] border border-emerald-300/20 bg-[radial-gradient(circle_at_90%_10%,rgba(52,211,153,0.2),transparent_30%),linear-gradient(135deg,#10231f,#0b1111)] p-6 sm:p-10"><Globe2 className="size-7 text-emerald-200" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-200">Publication Web App</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Préparez votre site pour le web.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-300">Vérifiez l’expérience, préparez votre domaine et gardez le contrôle de chaque étape de mise en ligne.</p></header><section className="mt-6 grid gap-4 md:grid-cols-3"><Step icon={<Monitor className="size-5" />} title="1. Vérifier" detail={hasBuild ? "Une version générée est disponible dans votre aperçu." : "Créez d’abord une version avant de préparer la publication."} action={<Button disabled={!hasBuild} onClick={() => navigate(`/projects/${projectId}/build`)} className="w-full bg-emerald-300 text-emerald-950 hover:bg-emerald-200">Voir l’aperçu</Button>} /><Step icon={<Globe2 className="size-5" />} title="2. Domaine" detail="Choisissez ou connectez un nom de domaine qui vous appartient." action={<Button variant="outline" onClick={() => navigate(`/projects/${projectId}/domains`)} className="w-full border-white/[0.14] bg-white/[0.04]">Gérer le domaine</Button>} /><Step icon={<ShieldCheck className="size-5" />} title="3. Mise en ligne" detail="La destination web publique est confirmée uniquement après publication vérifiée." action={<Button variant="outline" disabled className="w-full border-white/[0.14] bg-white/[0.04]">En attente de publication</Button>} /></section><section className="mt-6 rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-base font-semibold"><Link2 className="size-4 text-emerald-200" />Partage de l’aperçu</div><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Depuis l’onglet Aperçu, les boutons Ouvrir et Partager créent un accès isolé à votre version vérifiée, sans révéler vos fichiers source.</p></div><Button disabled={!hasBuild} onClick={() => navigate(`/projects/${projectId}/build`)} className="h-10 shrink-0 bg-white text-zinc-950 hover:bg-zinc-100">Retour à l’aperçu</Button></div></section></div></main></DashboardLayout>;
}

function Step({ icon, title, detail, action }: { icon: React.ReactNode; title: string; detail: string; action: React.ReactNode }) { return <article className="flex min-h-64 flex-col rounded-3xl border border-white/[0.08] bg-white/[0.025] p-5"><div className="text-emerald-200">{icon}</div><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-zinc-400">{detail}</p><div className="mt-5">{action}</div></article>; }
