import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useTheme } from "@/contexts/ThemeContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { CircleDollarSign, Github, Globe2, Languages, Moon, Palette, PlugZap, Settings2, Sparkles, Sun, UserRound } from "lucide-react";
import { useState } from "react";
import React from "react";

type Tab = "profile" | "preferences" | "integrations";
const tabs: { id: Tab; label: string; icon: typeof UserRound }[] = [
  { id: "profile", label: "Profil & Compte", icon: UserRound },
  { id: "preferences", label: "Préférences", icon: Palette },
  { id: "integrations", label: "Intégrations & Publication", icon: PlugZap },
];

export function AppearanceThemeChoices({ theme, setTheme }: { theme: "light" | "dark"; setTheme?: (next: "light" | "dark") => void }) { return <div className="grid gap-3 sm:grid-cols-2"><button aria-pressed={theme === "dark"} onClick={() => setTheme?.("dark")} className={`rounded-xl border p-4 text-left ${theme === "dark" ? "border-primary bg-primary/10" : "border-border"}`}><Moon className="size-4 text-primary" /><p className="mt-3 font-medium">Sombre</p></button><button aria-pressed={theme === "light"} onClick={() => setTheme?.("light")} className={`rounded-xl border p-4 text-left ${theme === "light" ? "border-primary bg-primary/10" : "border-border"}`}><Sun className="size-4 text-amber-400" /><p className="mt-3 font-medium">Clair</p></button></div>; }

export default function WorkspaceSettings() {
  const { user } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/settings" });
  const { theme, setTheme } = useTheme();
  const [tab, setTab] = useState<Tab>(() => new URLSearchParams(window.location.search).get("tab") === "billing" ? "profile" : (new URLSearchParams(window.location.search).get("tab") as Tab) || "profile");
  const [language, setLanguage] = useState("fr");
  const { data: balance } = trpc.billing.balance.useQuery(undefined, { enabled: Boolean(user) });
  const { data: packages = [] } = trpc.billing.packages.useQuery(undefined, { enabled: Boolean(user) });
  return <DashboardLayout><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-9"><section className="border-b border-border pb-6"><div className="inline-flex items-center gap-2 text-xs font-medium text-primary"><Settings2 className="size-3.5" />Compte Lakay</div><h1 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">Paramètres</h1><p className="mt-2 text-sm text-muted-foreground">Gérez votre compte et vos préférences.</p></section><div className="mt-6 flex gap-2 overflow-x-auto pb-1">{tabs.map(({ icon: Icon, ...item }) => <button key={item.id} onClick={() => setTab(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm ${tab === item.id ? "bg-primary text-primary-foreground" : "bg-card text-muted-foreground hover:bg-muted"}`}><Icon className="size-4" />{item.label}</button>)}</div><main className="mt-5 space-y-4">{tab === "profile" && <><Card icon={UserRound} title="Profil & Compte" detail="Vos informations de connexion."><div className="space-y-1"><p className="text-base font-semibold">{user?.name || "Membre Lakay"}</p><p className="text-sm text-muted-foreground">{user?.email}</p><p className="mt-4 text-sm font-medium">Plan actuel : Gratuit</p></div></Card><Plans balance={balance?.balance ?? 0} packages={packages as { id: string; label: string; credits: number }[]} /></>}{tab === "preferences" && <Card icon={Palette} title="Préférences" detail="Votre langue et votre apparence."><div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setTheme?.("dark")} className={`rounded-xl border p-4 text-left ${theme === "dark" ? "border-primary bg-primary/10" : "border-border"}`}><Moon className="size-4 text-primary" /><p className="mt-3 font-medium">Sombre</p></button><button onClick={() => setTheme?.("light")} className={`rounded-xl border p-4 text-left ${theme === "light" ? "border-primary bg-primary/10" : "border-border"}`}><Sun className="size-4 text-amber-400" /><p className="mt-3 font-medium">Clair</p></button></div><div className="mt-5 flex items-center justify-between gap-4 rounded-xl bg-muted p-4"><div><p className="font-medium">Langue</p><p className="text-sm text-muted-foreground">Langue de l’interface</p></div><Select value={language} onValueChange={setLanguage}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fr">Français</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></div></Card>}{tab === "integrations" && <Card icon={PlugZap} title="Intégrations & Publication" detail="Connectez vos outils lorsque vous êtes prêt."><Rows /></Card>}</main></div></DashboardLayout>;
}

function Plans({ balance, packages }: { balance: number; packages: { id: string; label: string; credits: number }[] }) { const cards = packages.length ? packages.map(item => ({ title: item.label, caption: `${item.credits} crédits` })) : [{ title: "500 crédits", caption: "Pour vos créations" }, { title: "1 000 crédits", caption: "Pour aller plus loin" }, { title: "Pass Illimité", caption: "Bientôt disponible" }]; return <Card icon={CircleDollarSign} title="Plans & Crédits" detail="Choisissez le rythme qui vous convient."><div className="rounded-2xl bg-gradient-to-br from-primary/15 to-emerald-400/5 p-5"><p className="text-xs font-medium text-primary">SOLDE DISPONIBLE</p><p className="mt-1 text-4xl font-semibold">{balance}</p><p className="text-sm text-muted-foreground">crédits Lakay</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{cards.map(card => <div key={card.title} className="rounded-xl border border-border bg-card p-4"><p className="font-semibold">{card.title}</p><p className="mt-1 text-xs text-muted-foreground">{card.caption}</p><Button disabled className="mt-4 w-full rounded-lg">Choisir</Button></div>)}</div></div></Card>; }
function Rows() { const items = [{ Icon: Github, title: "GitHub", detail: "Exportez votre code dans un dépôt." }, { Icon: PlugZap, title: "Supabase", detail: "Préparez votre base de données." }, { Icon: Globe2, title: "Domaine personnalisé", detail: "Utilisez votre propre adresse web." }]; return <div className="space-y-3">{items.map(({ Icon, title, detail }) => <div key={title} className="flex items-center justify-between gap-4 rounded-xl border border-border bg-muted p-4"><div className="flex items-center gap-3"><Icon className="size-5 text-primary" /><div><p className="font-medium">{title}</p><p className="text-sm text-muted-foreground">{detail}</p></div></div><Button disabled variant="outline">Connecter</Button></div>)}</div>; }
function Card({ icon: Icon, title, detail, children }: { icon: typeof UserRound; title: string; detail: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex gap-3"><Icon className="mt-0.5 size-5 text-primary" /><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div></div><div className="mt-5">{children}</div></section>; }
