import DashboardLayout from "@/components/DashboardLayout";
import { SettingsTabList, type SettingsTabOption } from "@/components/SettingsTabList";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useTheme } from "@/contexts/ThemeContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { applyWorkspacePreferences, DEFAULT_WORKSPACE_PREFERENCES, parseWorkspacePreferences, WORKSPACE_PREFERENCES_KEY, type WorkspacePreferences } from "@/lib/workspacePreferences";
import { BadgeCheck, CircleDollarSign, CreditCard, Github, Globe2, Languages, Link2, Moon, Palette, PlugZap, RotateCcw, Settings2, ShieldCheck, Sparkles, Sun, UserRound } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type SettingsTab = "profile" | "billing" | "integrations" | "appearance";
type LedgerEntry = { id: string; kind: string; amount: number; balanceAfter: number; operation: string | null; createdAt: Date | string };

const SETTINGS_TABS: SettingsTabOption[] = [
  { id: "profile", label: "Profil", note: "Identité & plan", icon: UserRound },
  { id: "billing", label: "Crédits & facturation", note: "Solde & historique", icon: CircleDollarSign },
  { id: "integrations", label: "Intégrations", note: "Code, données & publication", icon: PlugZap },
  { id: "appearance", label: "Apparence & langue", note: "Préférences workspace", icon: Palette },
];

export default function WorkspaceSettings() {
  const { user } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/settings" });
  const { theme, setTheme } = useTheme();
  const [preferences, setPreferences] = useState<WorkspacePreferences>(() => parseWorkspacePreferences(localStorage.getItem(WORKSPACE_PREFERENCES_KEY)));
  const [tab, setTab] = useState<SettingsTab>("profile");
  const { data: creditBalance } = trpc.billing.balance.useQuery(undefined, { enabled: Boolean(user) });
  const { data: ledger = [] } = trpc.billing.history.useQuery(undefined, { enabled: Boolean(user) });
  const history = ledger as LedgerEntry[];
  const initials = useMemo(() => (user?.name || user?.email || "L").split(/\s|@/).filter(Boolean).slice(0, 2).map(value => value[0]).join("").toUpperCase(), [user?.email, user?.name]);

  useEffect(() => {
    localStorage.setItem(WORKSPACE_PREFERENCES_KEY, JSON.stringify(preferences));
    applyWorkspacePreferences(document.documentElement, preferences);
  }, [preferences]);

  const setPreference = <Key extends keyof WorkspacePreferences>(key: Key, value: WorkspacePreferences[Key]) => setPreferences(current => ({ ...current, [key]: value }));
  const reset = () => { setPreferences(DEFAULT_WORKSPACE_PREFERENCES); toast.success("Préférences réinitialisées."); };

  return <DashboardLayout><div className="lakay-density-aware mx-auto max-w-6xl px-4 py-5 text-foreground sm:px-6 sm:py-8 lg:px-8">
    <section className="flex flex-col gap-5 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between sm:pb-8"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-[11px] font-medium text-primary"><Settings2 className="size-3.5" />Compte Lakay</div><h1 className="text-3xl font-semibold tracking-[-0.055em] text-foreground sm:text-4xl">Paramètres</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Gérez votre compte, vos crédits, vos connexions et la façon dont Lakay s’affiche.</p></div><Button variant="outline" onClick={reset} className="w-full rounded-xl border-border bg-card text-card-foreground hover:bg-muted sm:w-auto"><RotateCcw className="mr-2 size-4" />Réinitialiser</Button></section>
    <div className="mt-6 grid gap-4 lg:grid-cols-[0.78fr_1.42fr]"><aside className="rounded-2xl border border-border bg-card p-2.5"><p className="px-2.5 pb-2 pt-1 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Compte</p><SettingsTabList tabs={SETTINGS_TABS} activeTab={tab} onChange={id => setTab(id as SettingsTab)} /></aside><main id={`settings-panel-${tab}`} role="tabpanel" className="min-w-0">{tab === "profile" && <ProfileTab user={user} initials={initials} />}{tab === "billing" && <BillingTab balance={creditBalance?.balance ?? 0} history={history} />}{tab === "integrations" && <IntegrationsTab />}{tab === "appearance" && <AppearanceTab preferences={preferences} setPreference={setPreference} theme={theme} setTheme={setTheme} />}</main></div>
  </div></DashboardLayout>;
}

function ProfileTab({ user, initials }: { user: ReturnType<typeof useAuth>["user"]; initials: string }) { return <div className="space-y-4"><SettingCard icon={UserRound} title="Informations personnelles" description="Ces informations proviennent de votre compte Manus connecté."><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><Avatar className="size-16 border border-primary/25 bg-primary/10"><AvatarFallback className="bg-transparent text-lg font-semibold text-primary">{initials || "L"}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="text-base font-semibold text-foreground">{user?.name || "Compte Lakay"}</p><p className="mt-1 truncate text-sm text-muted-foreground">{user?.email || "Email non renseigné"}</p><p className="mt-2 text-xs text-muted-foreground">La photo et les informations de profil sont gérées par votre compte de connexion.</p></div><Badge className="w-fit border-0 bg-emerald-400/10 text-emerald-600 dark:text-emerald-300"><BadgeCheck className="mr-1 size-3.5" />Connecté</Badge></div></SettingCard><SettingCard icon={Sparkles} title="Plan Lakay" description="Votre espace utilise actuellement les fonctionnalités disponibles pour ce projet."><div className="flex flex-col gap-3 rounded-xl border border-border bg-muted p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-foreground">Plan Gratuit</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Le passage à Pro sera disponible lorsqu’un catalogue de crédits et de facturation sera configuré.</p></div><Badge className="w-fit border-0 bg-primary/10 text-primary">Gratuit</Badge></div></SettingCard></div>; }

function BillingTab({ balance, history }: { balance: number; history: LedgerEntry[] }) { return <div className="space-y-4"><SettingCard icon={CreditCard} title="Crédits restants" description="Les crédits sont calculés côté serveur. Aucune modification du solde n’est possible depuis le navigateur."><div className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/15 to-fuchsia-400/5 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Solde disponible</p><p className="mt-2 text-4xl font-semibold tracking-[-0.05em] text-foreground">{balance}</p><p className="mt-1 text-sm text-muted-foreground">crédits Lakay</p><div className="mt-5 flex flex-wrap gap-2"><Button disabled className="rounded-lg bg-primary px-4 text-primary-foreground disabled:opacity-50"><CircleDollarSign className="mr-2 size-4" />Recharger</Button><Button disabled variant="outline" className="rounded-lg border-border bg-card text-card-foreground disabled:opacity-50">Passer à Pro</Button></div><p className="mt-3 text-xs text-muted-foreground">Les achats seront activés après la configuration des produits et prix de facturation.</p></div></SettingCard><SettingCard icon={CreditCard} title="Historique" description="Mouvements de crédits enregistrés de manière immuable pour votre compte.">{history.length ? <div className="divide-y divide-border rounded-xl border border-border bg-muted">{history.slice(0, 8).map(entry => <div key={entry.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-foreground">{entry.operation || entry.kind}</p><p className="mt-1 text-[11px] text-muted-foreground">{new Date(entry.createdAt).toLocaleString("fr-FR")}</p></div><div className="text-right"><p className={`text-sm font-semibold ${entry.amount >= 0 ? "text-emerald-600 dark:text-emerald-300" : "text-amber-600 dark:text-amber-200"}`}>{entry.amount >= 0 ? "+" : ""}{entry.amount}</p><p className="mt-1 text-[11px] text-muted-foreground">Solde {entry.balanceAfter}</p></div></div>)}</div> : <EmptyState icon={CreditCard} title="Aucun achat ou mouvement" detail="Votre historique apparaîtra ici après une recharge ou l’utilisation de crédits." />}</SettingCard></div>; }

function IntegrationsTab() { const host = typeof window === "undefined" ? "" : window.location.host; return <div className="space-y-4"><SettingCard icon={Github} title="GitHub" description="Exportez le code généré dans votre propre dépôt."><IntegrationRow icon={Github} name="GitHub" detail="Connexion non configurée pour ce projet." action="Connecter GitHub" /></SettingCard><SettingCard icon={PlugZap} title="Supabase" description="Préparez les projets Lakay pour une base de données et une authentification externes."><IntegrationRow icon={PlugZap} name="Supabase" detail="Connexion non configurée. Les clés ne sont jamais demandées dans l’interface Lakay." action="Connecter Supabase" /></SettingCard><SettingCard icon={Globe2} title="Publication & domaine" description="La prévisualisation Lakay est disponible dans un environnement protégé."><div className="flex flex-col gap-3 rounded-xl border border-border bg-muted p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-foreground">Domaine du projet</p><p className="mt-1 break-all font-mono text-xs text-muted-foreground">{host || "Domaine Lakay"}</p></div><Badge className="w-fit border-0 bg-emerald-400/10 text-emerald-600 dark:text-emerald-300">Prévisualisation active</Badge></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Les domaines personnalisés et la publication d’applications full-stack seront disponibles après l’activation du runner isolé.</p></SettingCard></div>; }

export function AppearanceThemeChoices({ theme, setTheme }: { theme: "light" | "dark"; setTheme?: (nextTheme: "light" | "dark") => void }) { return <div className="grid gap-3 sm:grid-cols-2"><button type="button" aria-pressed={theme === "dark"} onClick={() => setTheme?.("dark")} className={`rounded-xl border p-4 text-left ${theme === "dark" ? "border-primary/35 bg-primary/10" : "border-border bg-muted"}`}><Moon className="size-4 text-primary" /><p className="mt-3 text-sm font-medium text-foreground">Sombre</p><p className="mt-1 text-xs text-muted-foreground">Actuel par défaut</p></button><button type="button" aria-pressed={theme === "light"} onClick={() => setTheme?.("light")} className={`rounded-xl border p-4 text-left ${theme === "light" ? "border-primary/35 bg-primary/10" : "border-border bg-muted"}`}><Sun className="size-4 text-amber-600 dark:text-amber-200" /><p className="mt-3 text-sm font-medium text-foreground">Clair</p><p className="mt-1 text-xs text-muted-foreground">Alternative lumineuse</p></button></div>; }

function AppearanceTab({ preferences, setPreference, theme, setTheme }: { preferences: WorkspacePreferences; setPreference: <Key extends keyof WorkspacePreferences>(key: Key, value: WorkspacePreferences[Key]) => void; theme: "light" | "dark"; setTheme?: (nextTheme: "light" | "dark") => void }) { return <div className="space-y-4"><SettingCard icon={Palette} title="Apparence" description="Choisissez une interface simple et confortable sur tout écran."><AppearanceThemeChoices theme={theme} setTheme={setTheme} /><div className="mt-4 space-y-4 border-t border-border pt-4"><PreferenceRow label="Réduire les animations" detail="Limite les transitions non essentielles." checked={preferences.reduceMotion} onChange={value => setPreference("reduceMotion", value)} /><PreferenceRow label="Workspace compact" detail="Resserre les surfaces de travail sur les grands écrans." checked={preferences.compactWorkspace} onChange={value => setPreference("compactWorkspace", value)} /><PreferenceRow label="Ouvrir la preview après un build" detail="Affiche la prévisualisation plutôt que les fichiers après une génération." checked={preferences.autoPreview} onChange={value => setPreference("autoPreview", value)} /></div><div className="mt-4 flex items-center justify-between gap-3 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3"><div><p className="text-sm font-medium text-emerald-700 dark:text-emerald-100">Safe execution boundary</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Les clés API et l’exécution backend restent protégées par le serveur Lakay.</p></div><ShieldCheck className="size-4 shrink-0 text-emerald-600 dark:text-emerald-300" /></div></SettingCard><SettingCard icon={Languages} title="Langue" description="La langue de préférence est enregistrée dans votre workspace."><div className="flex flex-col gap-3 rounded-xl border border-border bg-muted p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-foreground">Langue de l’interface</p><p className="mt-1 text-xs text-muted-foreground">Le français est la langue par défaut de Lakay. La traduction étendue sera ajoutée progressivement.</p></div><Select value={preferences.language} onValueChange={value => setPreference("language", value as WorkspacePreferences["language"])}><SelectTrigger className="w-full border-border bg-card text-card-foreground sm:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fr">Français</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></div></SettingCard></div>; }

function IntegrationRow({ icon: Icon, name, detail, action }: { icon: typeof Github; name: string; detail: string; action: string }) { return <div className="flex flex-col gap-3 rounded-xl border border-border bg-muted p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-accent"><Icon className="size-4 text-accent-foreground" /></div><div><p className="text-sm font-medium text-foreground">{name}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></div><Button disabled variant="outline" className="rounded-lg border-border bg-card text-muted-foreground disabled:opacity-50"><Link2 className="mr-2 size-3.5" />{action}</Button></div>; }
function SettingCard({ icon: Icon, title, description, children }: { icon: typeof Palette; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 text-card-foreground sm:p-6"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10"><Icon className="size-4 text-primary" /></div><div><h2 className="font-semibold text-foreground">{title}</h2><p className="mt-1 text-sm leading-5 text-muted-foreground">{description}</p></div></div><div className="mt-5 space-y-4">{children}</div></section>; }
function PreferenceRow({ label, detail, checked, onChange }: { label: string; detail: string; checked: boolean; onChange: (checked: boolean) => void }) { return <div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-foreground">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div><Switch checked={checked} onCheckedChange={onChange} aria-label={label} /></div>; }
function EmptyState({ icon: Icon, title, detail }: { icon: typeof CreditCard; title: string; detail: string }) { return <div className="rounded-xl border border-dashed border-border bg-muted p-6 text-center"><Icon className="mx-auto size-5 text-muted-foreground" /><p className="mt-3 text-sm font-medium text-foreground">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
