import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { LakayMark } from "@/components/LakayMark";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { FolderPlus, LayoutDashboard, LogOut, PanelLeft, WandSparkles } from "lucide-react";
import { useLocation } from "wouter";

const navigation = [
  { icon: LayoutDashboard, label: "Projects", path: "/dashboard" },
  { icon: WandSparkles, label: "App builder", path: "/build" },
  { icon: FolderPlus, label: "New project", path: "/projects/new" },
];

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const { loading, user, logout } = useAuth();
  const [location, navigate] = useLocation();
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#0b0b10]"><div className="size-6 animate-pulse rounded-full bg-violet-400/70" /></div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#0b0b10] p-5"><div className="w-full max-w-sm rounded-2xl border border-white/10 bg-white/[0.035] p-7 text-center"><LakayMark className="justify-center" /><h1 className="mt-7 text-xl font-semibold tracking-[-0.04em] text-white">Your workspace is waiting.</h1><p className="mt-2 text-sm leading-6 text-zinc-500">Sign in with Manus to create and manage your Lakay projects.</p><Button onClick={() => startLogin()} className="mt-7 w-full rounded-xl bg-violet-400 font-semibold text-zinc-950 hover:bg-violet-300">Continue with Manus</Button></div></div>;
  return <SidebarProvider defaultOpen><Sidebar className="border-r border-white/[0.07] bg-[#0e0e13] text-zinc-400"><SidebarHeader className="h-20 justify-center px-4"><div className="flex items-center justify-between"><LakayMark /><button onClick={() => navigate("/dashboard")} className="hidden size-8 place-items-center rounded-lg text-zinc-600 transition-colors hover:bg-white/5 hover:text-zinc-200 group-data-[collapsible=icon]:grid" aria-label="Open projects"><PanelLeft className="size-4" /></button></div></SidebarHeader><SidebarContent className="px-3"><SidebarMenu>{navigation.map(item => { const active = item.path === "/build" ? location === "/build" || location.endsWith("/build") : item.path === "/dashboard" ? location === "/dashboard" || (location.startsWith("/projects/") && !location.endsWith("/build")) : location === item.path; return <SidebarMenuItem key={item.path}><SidebarMenuButton isActive={active} onClick={() => navigate(item.path)} tooltip={item.label} className="h-10 rounded-xl px-3 text-zinc-500 transition-colors hover:bg-white/[0.055] hover:text-zinc-200 data-[active=true]:bg-violet-400/[0.12] data-[active=true]:text-violet-100"><item.icon className="size-4" /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>; })}</SidebarMenu></SidebarContent><SidebarFooter className="p-3"><DropdownMenu><DropdownMenuTrigger asChild><button className="flex w-full items-center gap-3 rounded-xl p-2 text-left transition-colors hover:bg-white/[0.045] focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-400/60 group-data-[collapsible=icon]:justify-center"><Avatar className="size-7 border border-white/10"><AvatarFallback className="bg-violet-400/15 text-[11px] font-semibold text-violet-200">{user.name?.charAt(0).toUpperCase() || "L"}</AvatarFallback></Avatar><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="truncate text-xs font-medium text-zinc-300">{user.name || "Lakay member"}</p><p className="mt-0.5 truncate text-[10px] text-zinc-600">{user.email || "Signed in with Manus"}</p></div></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48 border-white/10 bg-[#1a1a20] text-zinc-300"><DropdownMenuItem onClick={logout} className="cursor-pointer text-red-300 focus:bg-red-400/10 focus:text-red-200"><LogOut className="mr-2 size-4" />Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar><SidebarInset className="min-h-screen bg-[#0b0b10]"><div className="sticky top-0 z-20 flex h-14 items-center border-b border-white/[0.07] bg-[#0b0b10]/85 px-3 backdrop-blur xl:hidden"><SidebarTrigger className="rounded-lg text-zinc-400 hover:bg-white/5 hover:text-white" /><span className="ml-2 text-xs font-medium text-zinc-500">Lakay workspace</span></div><main className="min-h-screen">{children}</main></SidebarInset></SidebarProvider>;
}
